#!/bin/sh
#
# PROVIDE: ipblocker
# REQUIRE: NETWORKING syslogd
# 
# Define ipblocker_* variables in one of these files:
#	/etc/rc.conf
#	/etc/rc.conf.local

. /etc/rc.subr

name=ipblockerd
rcvar=`set_rcvar`

# read configuration and set defaults
load_rc_config ${name}
: ${ipblocker_enable:="NO"}
: ${ipblocker_config:="/usr/local/etc/ipblocker/ipblocker.conf"}

command="/usr/local/etc/ipblocker/${name}"
start_cmd="start_cmd"
stop_cmd="stop_cmd"
restart_cmd="restart_cmd"

start_cmd()
{
	${command} start ${ipblocker_config}
}

stop_cmd()
{
	${command} stop ${ipblocker_config}
}

restart_cmd()
{
	${command} stop  ${ipblocker_config}
	${command} start ${ipblocker_config}
}

run_rc_command "$1"
